### Numpy supports statistical mathematical functions:
- Min, max
- Median, mode, mean
- Std. Dev, Variance

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4],[7,6,2,0]])

print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [5]:
print(np.min(a))

0


In [8]:
#For axis specific:
print(np.min(a, axis=1))
print(np.max(a, axis=0))

[1 0]
[7 6 3 4]


In [9]:
#Similarly with all other functions
print(np.mean(a, axis=1))

[2.5  3.75]


In [10]:
print(np.std(a, axis = 0))

[3.  2.  0.5 2. ]


### `Mean` vs `Average`
- Mean is non-weighted, Average can be weighted

In [11]:
c = np.array([1,5,4,2,0])
print(np.mean(c))
print(np.average(c))

2.4
2.4


In [12]:
# But with weights
w = np.array([1,2,3,4,5])

print(np.average(c, weights=w))

2.066666666666667


In [14]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
a.tolist()

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [19]:
a.size

9

In [21]:
a = np.random.randint(0,15, size=(4,4))
a[(a >= 5) & (a <= 10)]

array([6, 9, 7, 6, 5, 6])

In [22]:
a[np.where((a >= 5) & (a <= 10))]

array([6, 9, 7, 6, 5, 6])

In [23]:
a[np.all((a >= 5) & (a <= 10))]

array([], shape=(0, 4, 4), dtype=int64)

In [24]:
a[np.any((a >= 5) & (a <= 10))]

array([[[ 6,  9,  7, 13],
        [ 0, 11,  6, 12],
        [14,  2,  0,  5],
        [13,  6,  1,  2]]])

In [34]:
a = np.arange(1, 31)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [35]:
a = a.resize((6,5))
print(a)

None
