## Numpy
- A library for mathematical calculations

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [5]:
a.shape

(5,)

In [6]:
b = np.array([a,a,a])
type(b)

numpy.ndarray

In [7]:
b.shape

(3, 5)

In [8]:
#Creating arrays
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
a = np.full((2,3), 5)
print(a)

[[5 5 5]
 [5 5 5]]


In [10]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
#Random array
r = np.random.random((3,4))
print(r)

[[0.03014476 0.28853687 0.03154354 0.97808137]
 [0.86355966 0.90314979 0.97654667 0.7249648 ]
 [0.62385824 0.3995142  0.73844781 0.83004848]]


In [12]:
# 2D Slicing
print(r[1:3,2:4])

[[0.97654667 0.7249648 ]
 [0.73844781 0.83004848]]


In [13]:
#Setting arrays
z = np.zeros((3,3))
z[1, :] = 5 #Set 1st row as 5s
z[:, -1] = 7 #Set last column as 7s

print(z)

[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [14]:
print(z.dtype)

float64


In [15]:
#For int
z = np.zeros((3,3), dtype=np.int64)
z[1, :] = 5 
z[:, -1] = 7 

print(z)

[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [16]:
z.dtype

dtype('int64')

Numpy also handles mathematical operations just like mathematical matrices

In [17]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [18]:
print(x+y)

[[ 6  8]
 [10 12]]


In [19]:
#Similar
print(np.add(x, y))

[[ 6  8]
 [10 12]]


In [20]:
print(x*y)

[[ 5 12]
 [21 32]]


This multiplication is element wise
For matrix multiplication, use `.dot`

In [21]:
print(x.dot(y))

[[19 22]
 [43 50]]


This gives the dot product aka Matrix Multiplication

We can get rowise sum, and columnwise sum using `axis`

In [22]:
a = np.array([[1,2],[3,4]])

print(np.sum(a))

10


In [23]:
#Column -> Axis = 0
#Row -> Axis = 1

print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[4 6]
[3 7]


In [24]:
a = np.array([1,2,3,4])

a*2

array([2, 4, 6, 8])

In [25]:
a**2

array([ 1,  4,  9, 16])

In [26]:
#stacking an array
np.stack((a, a**2), axis = 1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])